## Playing with Numpy & Pandas

Importing the numpy and Pandas into the notebook

In [2]:
import numpy as np
import pandas as pd

Assiging an array to a variable using np

In [3]:
a=np.array([34,43,43,434,2,4,4])

Finding the mean,size,shape and dimensions of the variable assigned using the attributes of numpy. 

In [15]:
print('mean of a:',a.mean())
print('size of a:',a.size)
print('shape of a:',a.shape )
print('dinmension of a:',a.ndim)

mean of a: 80.57142857142857
size of a: 7
shape of a: (7,)
dinmension of a: 1


Can also view the vairable as different datatype 

In [10]:
a.astype(float)

array([ 34.,  43.,  43., 434.,   2.,   4.,   4.])

Can assign a random list(array) of items to a variable using numpy 

In [16]:
b=np.arange(1,21)

In [17]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Finding the size,shape and dimensions of the variable created using the attributes of numpy

In [20]:
print('Shape:',b.shape)
print('Size:',b.size)
print('dimension:',b.ndim)

Shape: (20,)
Size: 20
dimension: 1


Using the reshape attribute to change the shape of the variable

In [29]:
b1=b.reshape(5,4) #5 rows and 4 columns
b2=b.reshape(4,5) #4 rows and 5 columns

print("b1:\n",b1)
print("\nb2:\n",b2)

b1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

b2:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


#### Scalar operations

In [22]:
b1*10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [30]:
b1+10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

Multiplication is possible as b1 has 5*4 and b2 has 4*5.. Thus resulting a 5*5 matrix

In [31]:
b1.dot(b2)

array([[110, 120, 130, 140, 150],
       [246, 272, 298, 324, 350],
       [382, 424, 466, 508, 550],
       [518, 576, 634, 692, 750],
       [654, 728, 802, 876, 950]])

Multiplication is not possible as b1 has 5*4 and a has 1 dimension

In [32]:
b1.dot(a)

ValueError: shapes (5,4) and (7,) not aligned: 4 (dim 1) != 7 (dim 0)

Transpose is possible

In [35]:
print('b1:\n',b1)
print('Transpose:\n',b1.transpose())

b1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Transpose:
 [[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


Create a 2*2 matrix using numpy array

In [40]:
c=np.array([[1.,2.],[3.,4.]])

In [43]:
c

array([[1., 2.],
       [3., 4.]])

Inverse of an array/matrix can be found using this attribute

In [39]:
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

creating a 2*2 array and reshaping it for further operations

In [44]:
d=np.array(np.arange(9).reshape(3,3),dtype=float)

In [45]:
d

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [48]:
#print 1.,4.,7.
#d[:,-2]
d[:,1]


array([1., 4., 7.])

In [52]:
#print 1,2,4,5
d[:2,1:]

array([[1., 2.],
       [4., 5.]])

In [54]:
#print 1,2,4,5,7,8
#d[:,1:]
d[:,-2:]

array([[1., 2.],
       [4., 5.],
       [7., 8.]])

In [55]:
#print 3,4,6,7
d[1:3,0:2]

array([[3., 4.],
       [6., 7.]])

In [59]:
d[d>5]

array([6., 7., 8.])

create an 1d array by simmply assiging a list of items to a variable

In [56]:
e=[23,3,4,34,34,3,43,43,4]

[43, 43, 4]

In [57]:
e[6:]

[43, 43, 4]

In [58]:
e[-3:]

[43, 43, 4]

create an array of zeroes and ones from numpy

In [61]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create 5*5 matirix with 5 using numpy.ones and numpy.zeros

In [64]:
(np.ones(25)*5).reshape(5,5)

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [65]:
np.ones(25).reshape(5,5)*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [66]:
np.zeros(25).reshape(5,5)+5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

#### Constructing a Dataframe from a Dictionary

In [68]:
Name_Age={'name':['Raghav','Sharmi','Ishaan'],'Age':[28,28,1]}

In [69]:
type(Name_Age)

dict

In [70]:
family=pd.DataFrame(Name_Age)

In [71]:
family
#By default, row labels(Index) are from the range(0-3) as we have 3 records

name  Age
0  Raghav   28
1  Sharmi   28
2  Ishaan    1

In [72]:
type(family)

pandas.core.frame.DataFrame

#### Broadcasting with a dictionary

In [74]:
new_data=np.arange(150)

new_col={'new_column':new_data,'sex':'M'}

new_column=pd.DataFrame(new_col)

In [75]:
new_column.head(5)

new_column sex
0           0   M
1           1   M
2           2   M
3           3   M
4           4   M

In [76]:
new_column.tail(5)

new_column sex
145         145   M
146         146   M
147         147   M
148         148   M
149         149   M

In [78]:
#change the column index and Column name

new_column.index=np.arange(150,300)

In [79]:
new_column.columns=['numbers','gender']

In [80]:
new_column.head(5)

numbers gender
150        0      M
151        1      M
152        2      M
153        3      M
154        4      M

#### Combining and Merging DataSets

Create multiple Dataframes for different datasets



Use concat/Merge to join the datasets. 

In [81]:
test_dataA={'Id':[100,101,102,103,104],'First_Name':['Raghav','Sankar','Akhil','Deepa','Sufiya'],'Last_Name':['v','Jayaram','Vijayan','Nayak','Taranam']}

In [82]:
df1=pd.DataFrame(test_dataA,columns=['Id','First_Name','Last_Name'])

In [83]:
test_dataB={'Id':[105,106,107,108,109],'First_Name':['Renju','Saurabh','Pradeep','Joshua','Mythreyi'],'Last_Name':['Nair','Indulkar','Bhat','Singh','Matada']}

In [84]:
df2=pd.DataFrame(test_dataB,columns=['Id','First_Name','Last_Name'])

In [85]:
df1

Id First_Name Last_Name
0  100     Raghav         v
1  101     Sankar   Jayaram
2  102      Akhil   Vijayan
3  103      Deepa     Nayak
4  104     Sufiya   Taranam

In [86]:
df2

Id First_Name Last_Name
0  105      Renju      Nair
1  106    Saurabh  Indulkar
2  107    Pradeep      Bhat
3  108     Joshua     Singh
4  109   Mythreyi    Matada

In [87]:
df_join=pd.concat([df1,df2])

In [88]:
df_join

Id First_Name Last_Name
0  100     Raghav         v
1  101     Sankar   Jayaram
2  102      Akhil   Vijayan
3  103      Deepa     Nayak
4  104     Sufiya   Taranam
0  105      Renju      Nair
1  106    Saurabh  Indulkar
2  107    Pradeep      Bhat
3  108     Joshua     Singh
4  109   Mythreyi    Matada

In [89]:
testdataC={'Id':[100,101,102,103,104,105,106,107,108,109],'Expense_Id':[100,200,260,500,490,600,390,290,340,111]}

In [90]:
df3=pd.DataFrame(testdataC,columns=['Id','Expense_Id'])

In [91]:
df3

Id  Expense_Id
0  100         100
1  101         200
2  102         260
3  103         500
4  104         490
5  105         600
6  106         390
7  107         290
8  108         340
9  109         111

In [92]:
pd.merge(df_join,df3,on='Id')

Id First_Name Last_Name  Expense_Id
0  100     Raghav         v         100
1  101     Sankar   Jayaram         200
2  102      Akhil   Vijayan         260
3  103      Deepa     Nayak         500
4  104     Sufiya   Taranam         490
5  105      Renju      Nair         600
6  106    Saurabh  Indulkar         390
7  107    Pradeep      Bhat         290
8  108     Joshua     Singh         340
9  109   Mythreyi    Matada         111

#### String Manipulation

In [93]:
string='India is my country'

In [94]:
#capitalize() helps to change the first letter of the string to capitalize

uppercase= string.capitalize()

In [95]:
uppercase

'India is my country'

In [96]:
#islower() helps to check whether the full string has lower case or not.. Returns TRUE or FALSE 

string.islower()

False

In [97]:
#isupper() helps to check whether the full string has upper case or not.. Returns TRUE or FALSE 

string.isupper()

False

In [98]:
#len() helps to find the count of the letters available in the string.. returns 'int' datatype

len(string)

19

In [99]:
#lower() helps to lower all the letters available in the string.
#upper() helps to upper all the letters available in the string.

string.lower()

'india is my country'

In [100]:
#title() helps to capitalise the first letter of all the words in a string. 

string.title()

'India Is My Country'

In [101]:
#swapcase() helps to convert all the letters available in the sring to convert to reversecase

string.swapcase()

'iNDIA IS MY COUNTRY'

### We shall discuss more on the other topics later.. Keep following... 


### Thanks.. 

### Happieeeee Learning... 